### ISSUE TITLE
Color issue on PocketGo 2

### ISSUE THREAD

**Issue by sardaukar** [gameblabla/pcsx4all_rs97_rg350#1]
Hey, your build of PCSX4All is really full of features, but the colors are off on the Pocket Go 2. Is it possible for a build to fix it? Thanks!

**Comment by gameblabla** [comment]
PCSX4ALL (my build of it) is making use of BGR color space. The stock firmware does not support BGR colorspace, only the Rogue CFW for the PG2 does. There are no plans to support the stock firmware as it has too many issues. Please use Rogue CFW if possible.
